/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDivitrend__factory } from "./IDivitrend__factory";
export { ITrndFactories__factory } from "./ITrndFactories__factory";
