/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IDivitrendInterface extends utils.Interface {
  functions: {
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "createSnapshot()": FunctionFragment;
    "currentSnapshotId()": FunctionFragment;
    "depositTax(uint256)": FunctionFragment;
    "disableBlacklist(address)": FunctionFragment;
    "enableBlacklist(address)": FunctionFragment;
    "exclude(address)": FunctionFragment;
    "getAutoSwap()": FunctionFragment;
    "getBuyTax()": FunctionFragment;
    "getCollectedTaxes()": FunctionFragment;
    "getDivitrendRewardsAddress()": FunctionFragment;
    "getExchangeAddress()": FunctionFragment;
    "getFounderPerc()": FunctionFragment;
    "getFounderWallet()": FunctionFragment;
    "getLiquidityPerc()": FunctionFragment;
    "getLiquidityWallet()": FunctionFragment;
    "getPairAddress()": FunctionFragment;
    "getRouterAddress()": FunctionFragment;
    "getSellTax()": FunctionFragment;
    "getStakedCapPerc()": FunctionFragment;
    "getStakedCapitalWallet()": FunctionFragment;
    "getSwapThreshold()": FunctionFragment;
    "getUniswapV2Factory()": FunctionFragment;
    "getUniswapV2Pair()": FunctionFragment;
    "isBlacklisted(address)": FunctionFragment;
    "isExcluded(address)": FunctionFragment;
    "manualSwapAndLiquify()": FunctionFragment;
    "pause()": FunctionFragment;
    "removeExclude(address)": FunctionFragment;
    "setAutoSwap(bool)": FunctionFragment;
    "setBuyTax(uint8)": FunctionFragment;
    "setDivitrendRewardsAddress(address)": FunctionFragment;
    "setExchangeAddress(address)": FunctionFragment;
    "setFounderPerc(uint16)": FunctionFragment;
    "setFounderWallet(address)": FunctionFragment;
    "setLiquidityPerc(uint16)": FunctionFragment;
    "setLiquidityWallet(address)": FunctionFragment;
    "setRouterAddress(address)": FunctionFragment;
    "setSellTax(uint8)": FunctionFragment;
    "setStakedCapPerc(uint16)": FunctionFragment;
    "setStakedCapitalWallet(address)": FunctionFragment;
    "setSwapThreshold(uint256)": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "unpause()": FunctionFragment;
    "withdrawETH()": FunctionFragment;
    "withdrawTokens(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allowance"
      | "approve"
      | "balanceOf"
      | "createSnapshot"
      | "currentSnapshotId"
      | "depositTax"
      | "disableBlacklist"
      | "enableBlacklist"
      | "exclude"
      | "getAutoSwap"
      | "getBuyTax"
      | "getCollectedTaxes"
      | "getDivitrendRewardsAddress"
      | "getExchangeAddress"
      | "getFounderPerc"
      | "getFounderWallet"
      | "getLiquidityPerc"
      | "getLiquidityWallet"
      | "getPairAddress"
      | "getRouterAddress"
      | "getSellTax"
      | "getStakedCapPerc"
      | "getStakedCapitalWallet"
      | "getSwapThreshold"
      | "getUniswapV2Factory"
      | "getUniswapV2Pair"
      | "isBlacklisted"
      | "isExcluded"
      | "manualSwapAndLiquify"
      | "pause"
      | "removeExclude"
      | "setAutoSwap"
      | "setBuyTax"
      | "setDivitrendRewardsAddress"
      | "setExchangeAddress"
      | "setFounderPerc"
      | "setFounderWallet"
      | "setLiquidityPerc"
      | "setLiquidityWallet"
      | "setRouterAddress"
      | "setSellTax"
      | "setStakedCapPerc"
      | "setStakedCapitalWallet"
      | "setSwapThreshold"
      | "transfer"
      | "transferFrom"
      | "unpause"
      | "withdrawETH"
      | "withdrawTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allowance",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentSnapshotId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositTax",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "disableBlacklist",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "enableBlacklist",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "exclude",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAutoSwap",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getBuyTax", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCollectedTaxes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDivitrendRewardsAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExchangeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFounderPerc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFounderWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityPerc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPairAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRouterAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSellTax",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakedCapPerc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakedCapitalWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUniswapV2Factory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUniswapV2Pair",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isExcluded",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "manualSwapAndLiquify",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeExclude",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAutoSwap",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setBuyTax",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setDivitrendRewardsAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setExchangeAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFounderPerc",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFounderWallet",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLiquidityPerc",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLiquidityWallet",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRouterAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSellTax",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakedCapPerc",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakedCapitalWallet",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSwapThreshold",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTokens",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentSnapshotId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositTax", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disableBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exclude", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAutoSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBuyTax", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCollectedTaxes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDivitrendRewardsAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExchangeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFounderPerc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFounderWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityPerc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPairAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRouterAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSellTax", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStakedCapPerc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakedCapitalWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSwapThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUniswapV2Factory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUniswapV2Pair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isExcluded", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manualSwapAndLiquify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeExclude",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutoSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBuyTax", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDivitrendRewardsAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExchangeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFounderPerc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFounderWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLiquidityPerc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLiquidityWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRouterAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSellTax", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setStakedCapPerc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakedCapitalWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSwapThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokens",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IDivitrend extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDivitrendInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    approve(
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    createSnapshot(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentSnapshotId(overrides?: CallOverrides): Promise<[BigNumber]>;

    depositTax(
      taxAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disableBlacklist(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    enableBlacklist(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    exclude(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAutoSwap(overrides?: CallOverrides): Promise<[boolean]>;

    getBuyTax(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCollectedTaxes(overrides?: CallOverrides): Promise<[BigNumber]>;

    getDivitrendRewardsAddress(overrides?: CallOverrides): Promise<[string]>;

    getExchangeAddress(overrides?: CallOverrides): Promise<[string]>;

    getFounderPerc(overrides?: CallOverrides): Promise<[BigNumber]>;

    getFounderWallet(overrides?: CallOverrides): Promise<[string]>;

    getLiquidityPerc(overrides?: CallOverrides): Promise<[BigNumber]>;

    getLiquidityWallet(overrides?: CallOverrides): Promise<[string]>;

    getPairAddress(overrides?: CallOverrides): Promise<[string]>;

    getRouterAddress(overrides?: CallOverrides): Promise<[string]>;

    getSellTax(overrides?: CallOverrides): Promise<[BigNumber]>;

    getStakedCapPerc(overrides?: CallOverrides): Promise<[BigNumber]>;

    getStakedCapitalWallet(overrides?: CallOverrides): Promise<[string]>;

    getSwapThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    getUniswapV2Factory(overrides?: CallOverrides): Promise<[string]>;

    getUniswapV2Pair(overrides?: CallOverrides): Promise<[string]>;

    isBlacklisted(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isExcluded(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    manualSwapAndLiquify(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeExclude(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAutoSwap(
      value: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBuyTax(
      tax: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDivitrendRewardsAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setExchangeAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFounderPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFounderWallet(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLiquidityPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLiquidityWallet(
      account: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRouterAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSellTax(
      tax: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setStakedCapPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setStakedCapitalWallet(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSwapThreshold(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transfer(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferFrom(
      sender: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawETH(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawTokens(
      tokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  allowance(
    owner: PromiseOrValue<string>,
    spender: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  balanceOf(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  createSnapshot(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentSnapshotId(overrides?: CallOverrides): Promise<BigNumber>;

  depositTax(
    taxAmount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disableBlacklist(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  enableBlacklist(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  exclude(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAutoSwap(overrides?: CallOverrides): Promise<boolean>;

  getBuyTax(overrides?: CallOverrides): Promise<BigNumber>;

  getCollectedTaxes(overrides?: CallOverrides): Promise<BigNumber>;

  getDivitrendRewardsAddress(overrides?: CallOverrides): Promise<string>;

  getExchangeAddress(overrides?: CallOverrides): Promise<string>;

  getFounderPerc(overrides?: CallOverrides): Promise<BigNumber>;

  getFounderWallet(overrides?: CallOverrides): Promise<string>;

  getLiquidityPerc(overrides?: CallOverrides): Promise<BigNumber>;

  getLiquidityWallet(overrides?: CallOverrides): Promise<string>;

  getPairAddress(overrides?: CallOverrides): Promise<string>;

  getRouterAddress(overrides?: CallOverrides): Promise<string>;

  getSellTax(overrides?: CallOverrides): Promise<BigNumber>;

  getStakedCapPerc(overrides?: CallOverrides): Promise<BigNumber>;

  getStakedCapitalWallet(overrides?: CallOverrides): Promise<string>;

  getSwapThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  getUniswapV2Factory(overrides?: CallOverrides): Promise<string>;

  getUniswapV2Pair(overrides?: CallOverrides): Promise<string>;

  isBlacklisted(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isExcluded(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  manualSwapAndLiquify(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeExclude(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAutoSwap(
    value: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBuyTax(
    tax: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDivitrendRewardsAddress(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setExchangeAddress(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFounderPerc(
    perc: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFounderWallet(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLiquidityPerc(
    perc: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLiquidityWallet(
    account: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRouterAddress(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSellTax(
    tax: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setStakedCapPerc(
    perc: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setStakedCapitalWallet(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSwapThreshold(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transfer(
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferFrom(
    sender: PromiseOrValue<string>,
    recipient: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawETH(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawTokens(
    tokenAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createSnapshot(overrides?: CallOverrides): Promise<void>;

    currentSnapshotId(overrides?: CallOverrides): Promise<BigNumber>;

    depositTax(
      taxAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    disableBlacklist(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    enableBlacklist(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    exclude(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAutoSwap(overrides?: CallOverrides): Promise<boolean>;

    getBuyTax(overrides?: CallOverrides): Promise<BigNumber>;

    getCollectedTaxes(overrides?: CallOverrides): Promise<BigNumber>;

    getDivitrendRewardsAddress(overrides?: CallOverrides): Promise<string>;

    getExchangeAddress(overrides?: CallOverrides): Promise<string>;

    getFounderPerc(overrides?: CallOverrides): Promise<BigNumber>;

    getFounderWallet(overrides?: CallOverrides): Promise<string>;

    getLiquidityPerc(overrides?: CallOverrides): Promise<BigNumber>;

    getLiquidityWallet(overrides?: CallOverrides): Promise<string>;

    getPairAddress(overrides?: CallOverrides): Promise<string>;

    getRouterAddress(overrides?: CallOverrides): Promise<string>;

    getSellTax(overrides?: CallOverrides): Promise<BigNumber>;

    getStakedCapPerc(overrides?: CallOverrides): Promise<BigNumber>;

    getStakedCapitalWallet(overrides?: CallOverrides): Promise<string>;

    getSwapThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    getUniswapV2Factory(overrides?: CallOverrides): Promise<string>;

    getUniswapV2Pair(overrides?: CallOverrides): Promise<string>;

    isBlacklisted(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isExcluded(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    manualSwapAndLiquify(overrides?: CallOverrides): Promise<void>;

    pause(overrides?: CallOverrides): Promise<void>;

    removeExclude(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setAutoSwap(
      value: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setBuyTax(
      tax: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDivitrendRewardsAddress(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setExchangeAddress(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFounderPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFounderWallet(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLiquidityPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLiquidityWallet(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRouterAddress(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSellTax(
      tax: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setStakedCapPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setStakedCapitalWallet(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSwapThreshold(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transfer(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferFrom(
      sender: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    unpause(overrides?: CallOverrides): Promise<void>;

    withdrawETH(overrides?: CallOverrides): Promise<void>;

    withdrawTokens(
      tokenAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createSnapshot(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentSnapshotId(overrides?: CallOverrides): Promise<BigNumber>;

    depositTax(
      taxAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disableBlacklist(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    enableBlacklist(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    exclude(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAutoSwap(overrides?: CallOverrides): Promise<BigNumber>;

    getBuyTax(overrides?: CallOverrides): Promise<BigNumber>;

    getCollectedTaxes(overrides?: CallOverrides): Promise<BigNumber>;

    getDivitrendRewardsAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getExchangeAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getFounderPerc(overrides?: CallOverrides): Promise<BigNumber>;

    getFounderWallet(overrides?: CallOverrides): Promise<BigNumber>;

    getLiquidityPerc(overrides?: CallOverrides): Promise<BigNumber>;

    getLiquidityWallet(overrides?: CallOverrides): Promise<BigNumber>;

    getPairAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getRouterAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getSellTax(overrides?: CallOverrides): Promise<BigNumber>;

    getStakedCapPerc(overrides?: CallOverrides): Promise<BigNumber>;

    getStakedCapitalWallet(overrides?: CallOverrides): Promise<BigNumber>;

    getSwapThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    getUniswapV2Factory(overrides?: CallOverrides): Promise<BigNumber>;

    getUniswapV2Pair(overrides?: CallOverrides): Promise<BigNumber>;

    isBlacklisted(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isExcluded(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    manualSwapAndLiquify(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeExclude(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAutoSwap(
      value: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBuyTax(
      tax: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDivitrendRewardsAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setExchangeAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFounderPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFounderWallet(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLiquidityPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLiquidityWallet(
      account: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRouterAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSellTax(
      tax: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setStakedCapPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setStakedCapitalWallet(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSwapThreshold(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transfer(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferFrom(
      sender: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawETH(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawTokens(
      tokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createSnapshot(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentSnapshotId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositTax(
      taxAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disableBlacklist(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    enableBlacklist(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    exclude(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAutoSwap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBuyTax(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCollectedTaxes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDivitrendRewardsAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getExchangeAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFounderPerc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFounderWallet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLiquidityPerc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLiquidityWallet(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPairAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRouterAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSellTax(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStakedCapPerc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStakedCapitalWallet(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSwapThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUniswapV2Factory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUniswapV2Pair(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isBlacklisted(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isExcluded(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    manualSwapAndLiquify(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeExclude(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAutoSwap(
      value: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBuyTax(
      tax: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDivitrendRewardsAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setExchangeAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFounderPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFounderWallet(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLiquidityPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLiquidityWallet(
      account: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRouterAddress(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSellTax(
      tax: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setStakedCapPerc(
      perc: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setStakedCapitalWallet(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSwapThreshold(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transfer(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferFrom(
      sender: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawETH(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawTokens(
      tokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
