/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as diviTrendSol from "./DiviTrend.sol";
export type { diviTrendSol };
import type * as trndFactoriesSol from "./TrndFactories.sol";
export type { trndFactoriesSol };
import type * as trndRewardsSol from "./TrndRewards.sol";
export type { trndRewardsSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
